// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['users']['UserService']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['users']['UserService']['DeleteUser'](arg1);
}

export function GetUser(arg1) {
  return window['go']['users']['UserService']['GetUser'](arg1);
}

export function GetUsers() {
  return window['go']['users']['UserService']['GetUsers']();
}

export function UpdateUser(arg1) {
  return window['go']['users']['UserService']['UpdateUser'](arg1);
}
