// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {users} from '../models';

export function CreateUser(arg1:users.UserDto):Promise<number>;

export function DeleteUser(arg1:number):Promise<void>;

export function GetUser(arg1:number):Promise<users.User>;

export function GetUsers():Promise<Array<users.User>>;

export function UpdateUser(arg1:users.User):Promise<void>;
