// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Check(arg1:number):Promise<models.Budget>;

export function Make(arg1:models.BudgetDto):Promise<models.Budget>;

export function Remove(arg1:number):Promise<void>;

export function Revise(arg1:number,arg2:models.BudgetDto):Promise<void>;
