// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check(arg1) {
  return window['go']['services']['BudgetService']['Check'](arg1);
}

export function Make(arg1) {
  return window['go']['services']['BudgetService']['Make'](arg1);
}

export function Remove(arg1) {
  return window['go']['services']['BudgetService']['Remove'](arg1);
}

export function Revise(arg1, arg2) {
  return window['go']['services']['BudgetService']['Revise'](arg1, arg2);
}
