// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['services']['CategoryService']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['services']['CategoryService']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['services']['CategoryService']['Get'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['services']['CategoryService']['Rename'](arg1, arg2);
}
