// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Add(arg1:string):Promise<models.Category>;

export function Delete(arg1:number):Promise<void>;

export function Get(arg1:number):Promise<models.Category>;

export function Rename(arg1:number,arg2:string):Promise<void>;
