// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Add(arg1:models.TransactionDto):Promise<models.Transaction>;

export function Check(arg1:number):Promise<models.Transaction>;

export function Remove(arg1:number):Promise<void>;

export function Revise(arg1:number,arg2:models.TransactionDto):Promise<void>;
