// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['services']['TransactionService']['Add'](arg1);
}

export function Check(arg1) {
  return window['go']['services']['TransactionService']['Check'](arg1);
}

export function Remove(arg1) {
  return window['go']['services']['TransactionService']['Remove'](arg1);
}

export function Revise(arg1, arg2) {
  return window['go']['services']['TransactionService']['Revise'](arg1, arg2);
}
