// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteProfile(arg1:number):Promise<void>;

export function GetAllProfiles():Promise<Array<models.User>>;

export function Login(arg1:number,arg2:string,arg3:string):Promise<models.User>;

export function Register(arg1:models.UserDto):Promise<models.User>;

export function UpdateProfile(arg1:number,arg2:models.UserDto):Promise<void>;
