// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['services']['UserService']['DeleteProfile'](arg1);
}

export function GetAllProfiles() {
  return window['go']['services']['UserService']['GetAllProfiles']();
}

export function Login(arg1, arg2, arg3) {
  return window['go']['services']['UserService']['Login'](arg1, arg2, arg3);
}

export function Register(arg1) {
  return window['go']['services']['UserService']['Register'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['services']['UserService']['UpdateProfile'](arg1, arg2);
}
